//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BlackhoefStudios.Common.ViewModels.Bases
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class BaseViewModel<T> : BaseViewModel
	{
		public virtual T DataSource
		{
			get;
			set;
		}

	}
}

