//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BlackhoefStudios.Common.ViewModels.Bases
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class BaseListItemViewModel
	{
		public virtual ICommand Delete
		{
			get;
			set;
		}

		public virtual ICommand Selected
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Subtitle
		{
			get;
			set;
		}

		public virtual string Id
		{
			get;
			set;
		}

		public BaseListItemViewModel()
		{
		}

	}
}

