//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BlackhoefStudios.Common.ViewModels.Bases
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using ViewModels.Interfaces;

	public abstract class BaseViewModel : INotifyPropertyChanged
	{
		public virtual bool IsBusy
		{
			get;
			set;
		}

		public virtual INavigation Navigation
		{
			get;
			set;
		}

		public virtual string Title
		{
			get;
			set;
		}

		public virtual void OnPropertyChanged(object String property)
		{
			throw new System.NotImplementedException();
		}

		protected BaseViewModel(object IApplication app)
		{
		}

	}
}

