//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BlackhoefStudios.Common.ViewModels.Bases
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class BaseListViewModel<T> : BaseViewModel
	{
		public virtual ICommand Refresh
		{
			get;
			set;
		}

		public virtual ObservableCollection<T> DataSource
		{
			get;
			set;
		}

		public virtual T Selected
		{
			get;
			set;
		}

	}
}

